services:
  mysql_206:
    env_file:
      - .env
    container_name: mysql_206
    image: mysql:8.0.33  # Versão estável comprovada
    restart: unless-stopped
    environment:
      MYSQL_ROOT_HOST: '%'
      TZ: America/Sao_Paulo
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password  # Config via env var
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-log-bin  # Desativa logs binários para simplificar
    volumes:
      - mysql_206_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_206_data: